copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'pt-BR'
relativeURLs = "True"
defaultContentLanguage = 'pt'
theme = 'enhanced-lowkey'
title = 'Diego Paiva'
enableRobotsTXT = true
summaryLength = 15
paginate = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4