version: '3.8'

services:
  entusiasta.dev:
    image: klakegg/hugo:0.111.3-ext-alpine
    container_name: entusiasta.dev
    command: server -D
    volumes:
      - ./src:/src
    ports:
      - 1313:1313
